### ISSUE TITLE
Decide on name

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/imklib2#4]
Candidates:
 - imklib(2)
 - ta.kt (tensor algebra for kotlin)
 - ma.kt (math? for kotlin)
 - na.kt (**n**ot just **a**lgebra for kotlin)
 - nu.kt (numpy kotlin but there is already kotlin-numpy and probably too numpy centric)
 - no.kt (n-dimensional opreations/opreators for kotlin)
 - fun.kt (functions for kotlin)
 - im.kt
 - spa.kt (spatial kotlin)
 - NumKo

See also: https://gitter.im/imglib/imglib2?at=5f35e8159ad3cd3205c78ad3

**Comment by raghavchhetri** [comment]
other suggestions: 
Numeric kit (kit as in a toolkit)
- NumKt 
- num.kt

Image kit
- ImgKt
- img.kt
- imglib2.kt

**Comment by axtimwalde** [comment]
My current preference in order:
1. na.kt
2. ta.kt
3. num.kt

**Comment by hanslovsky** [comment]
And we have a winner, ntakt!
